#!/bin/bash

set -eo pipefail

echo "Preparing to deploy to Production"

# Authenticate with Terminus
if [[ -z "$( terminus whoami )" ]]; then
  echo "Logging in to terminus"
  terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
else
  echo "Using existing terminus session"
fi

echo "Backing up Production."
terminus backup:create "$TERMINUS_SITE".live --element=db

echo "Deploying to Production"
terminus env:deploy "$TERMINUS_SITE".live

# We make the assummption that this script is being run from the project root.
if [ -f "./.circleci/scripts/drush-commands" ]; then
  ./.circleci/scripts/drush-commands $TERMINUS_SITE live $SYNC_CONFIG
else
  ./vendor/fourkitchens/pots/scripts/pantheon/drush-commands $TERMINUS_SITE live $SYNC_CONFIG
fi

echo "Done deploying. The site is now live."
