#!/bin/bash

set -eo pipefail

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

echo "Backing up Production."
terminus backup:create "$TERMINUS_SITE".live --element=db

echo "Deploying to Production"
terminus env:deploy "$TERMINUS_SITE".live

# We make the assummption that this script is being run from the project root.
if [ -f "./.circleci/scripts/drush-commands" ]; then
  ./.circleci/scripts/drush-commands $TERMINUS_SITE live $SYNC_CONFIG
else
  ./vendor/fourkitchens/project_ci/scripts/pantheon/drush-commands $TERMINUS_SITE live $SYNC_CONFIG
fi

echo "Done deploying. The site is now live."
