#!/bin/bash

set -eo pipefail

# Lint php code for syntax errors
find modules/custom themes/custom -name "*.php" '!' -path '*/node_modules/*' -print0 | xargs -0 -n1 -P8 php -l

# Check coding standards
#./vendor/bin/phpcs
